// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5sQluSQp5RpioDX8aM7Q9nLvrbLLTJk',
    appId: '1:529602438262:web:bd6567406ca430313d6b57',
    messagingSenderId: '529602438262',
    projectId: 'elostaaz-d0a19',
    authDomain: 'elostaaz-d0a19.firebaseapp.com',
    storageBucket: 'elostaaz-d0a19.appspot.com',
    measurementId: 'G-JVMBTZDMBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrmvCd0KceUpTudy03pyCPeQy3jW2EFR4',
    appId: '1:529602438262:android:5234ae06a27bd2793d6b57',
    messagingSenderId: '529602438262',
    projectId: 'elostaaz-d0a19',
    storageBucket: 'elostaaz-d0a19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtr49-DYYFwY80hadOysCY3qzh0_oKP-c',
    appId: '1:529602438262:ios:4af5d03ae6b813ad3d6b57',
    messagingSenderId: '529602438262',
    projectId: 'elostaaz-d0a19',
    storageBucket: 'elostaaz-d0a19.appspot.com',
    iosClientId: '529602438262-gtpah4jsqqeoj635qcevusikt39f4glv.apps.googleusercontent.com',
    iosBundleId: 'com.example.elostaaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtr49-DYYFwY80hadOysCY3qzh0_oKP-c',
    appId: '1:529602438262:ios:4af5d03ae6b813ad3d6b57',
    messagingSenderId: '529602438262',
    projectId: 'elostaaz-d0a19',
    storageBucket: 'elostaaz-d0a19.appspot.com',
    iosClientId: '529602438262-gtpah4jsqqeoj635qcevusikt39f4glv.apps.googleusercontent.com',
    iosBundleId: 'com.example.elostaaz',
  );
}
